import { Client, Message } from 'discord.js'
import cfg from './config'

export const cmd_help = ():string[] => [
    '———————————————————————————',
    '**# First time users                                                                              #**',
    '———————————————————————————',
    'Getting started is an easy X-step process:',
    '1) Create your account at https://profile.callofduty.com',
    '2) Sign in with your CallOfDuty account from Step #1 at https://stagg.co/login',
    '3) Relax while your match history is collected and try some of the commands below',
    '',
    '———————————————————————————',
    '**# Using the bot                                                                                  #**',
    '———————————————————————————',
    'If calling the bot in a text channel you will need to prefix messages with `%` or `@Stagg`; this is not necessary in DMs.',
    'DM example:',
    '```',
    'search MellowD',
    '```',
    'Text channel example:',
    '```',
    '% search MellowD',
    '```',
    '',
    'Available commands:',
    '- `help` Get help using the Stagg Discord bot',
    '- `meta` Get stats on the overall Stagg system',
    '- `register <email> OR <username> <platform>` Link your Discord',
    '- `search <username> <platform?>` Find profiles matching your query',
    '- `wz all <username> <platform?>` Show all aggregated BR stats',
    '- `wz solos <username> <platform?>` Aggregated stats from all BR Solos matches',
    '- `wz duos <username> <platform?>` Aggregated stats from all BR Duos matches',
    '- `wz trios <username> <platform?>` Aggregated stats from all BR Trios matches',
    '- `wz quads <username> <platform?>` Aggregated stats from all BR Quads matches',
    '- `wz combined <username> <platform?>` Aggregated stats from all BR modes',
    '',
    'Any arguments that end with `?` are optional (eg: `<platform?>`); default values are listed below:',
    '- `<platform?> = uno` (Activision)',
    '',
    'Additional support may be provided on an as-needed basis in the `#help` channel here: https://discord.gg/yV2RjJK',
    '',
    'If you want this humble binary buck in your server, click the link below:',
    'https://discord.com/oauth2/authorize?client_id=723179755548967027&scope=bot&permissions=67584',
]